/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:964934:
  //println("button1 - GButton >> GEvent." + event + " @ " + millis());
  x=0;
  y= random(-height/6);
  z=0;
  
  /* Posizione aleatoria di tiro a canestro */ 
  xR0 = random(-width/10, width/4);
  zR0 = random(-width/10, width/4);
  
  randomBallVel();
  
  pallaFerma = false;
  alreadyCheck = false;
  attivaLancio = false;
  arrivato = false;
  attivaCinematicaInversa = false;
  
  /* Variabili iniziali giunti del robot antropomorfo */
  q1REF = 0;
  q2REF = 0;
  q3REF = 0;


} //_CODE_:button1:964934:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Antropomorphe Basketball");
  button1 = new GButton(this, 650, 100, 134, 40);
  button1.setText("LAUNCH BALL");
  button1.setTextBold();
  button1.setTextItalic();
  button1.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
